import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Roboto_Flex as Roboto } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
    subsets: ["latin"],
    weight: "500",
    variable: "--font-roboto",
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.className} ${roboto.variable}`}>
                {children}
            </body>
        </html>
    );
}
